# Site settings
title: "xiaoming"
url: "//www.xiaoming.work/"
highlighter: pygments
paginate: 30
author:
    name: 小明
    github: hepanming007
    email:
    twitter:
    facebook:
    googleplus:
    weibo: 
atom_path: /atom.xml
rss_path: /rss.xml

# Build settings
markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]
permalink: /:categories/:year-:month/:title.html

assets_path: /assets
sass:
    sass_dir: assets/_sass
    style: :compressed

# comment
comments:
    changyan:
        status:0                           

# 网站统计


